### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by ms-gh-admin** [networktocode/diffsync#130]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [Update dependency bandit to v1.7.4](../pull/128)
 - [ ] [Update dependency coverage to v6.4.2](../pull/129)
 - [ ] [Update dependency redis to v4.3.4](../pull/131)
 - [ ] [Update dependency types-toml to v0.10.8](../pull/132)
 - [ ] [Update dependency black to v22.6.0](../pull/133)
 - [ ] [Update dependency mypy to v0.971](../pull/134)
 - [ ] [Update dependency pytest to v7.1.2](../pull/135)
 - [ ] [Update dependency types-redis to v4.3.11](../pull/136)
 - [ ] [Update dependency yamllint to v1.27.1](../pull/137)
 - [ ] **Click on this checkbox to rebase all open PRs at once**

## Ignored or Blocked

These are blocked by an existing closed PR and will not be recreated unless you click a checkbox below.

 - [ ] [Update dependency flake8 to v4](../pull/138)

## Detected dependencies

<details><summary>pip_requirements</summary>
<blockquote>

<details><summary>docs/requirements.txt</summary>

 - `m2r2 ==0.2.7`
 - `mistune ==0.8.4`
 - `sphinx ==4.5.0`
 - `toml ==0.10.2`
 - `sphinx-rtd-theme ==1.0.0`

</details>

</blockquote>
</details>

<details><summary>poetry</summary>
<blockquote>

<details><summary>pyproject.toml</summary>

 - `pydantic ^1.7.4,!=1.8,!=1.8.1`
 - `structlog >= 20.1.0, < 22.0.0`
 - `packaging ^21.3`
 - `colorama ^0.4.3`
 - `redis ^4.3`
 - `pytest *`
 - `pyyaml *`
 - `black *`
 - `pylint *`
 - `pydocstyle *`
 - `yamllint *`
 - `bandit *`
 - `invoke *`
 - `flake8 *`
 - `mypy *`
 - `pytest-cov *`
 - `pytest-structlog *`
 - `coverage *`
 - `Sphinx *`
 - `m2r2 *`
 - `sphinx-rtd-theme *`
 - `toml *`
 - `types-toml *`
 - `types-redis *`
 - `pytest-redislite ^0.1.0`
 - `redis `

</details>

</blockquote>
</details>

**Comment by Kircheneer** [comment]
See #148
