### ISSUE TITLE
`diffsync.DiffSync` naming

### ISSUE THREAD

**Issue by Kircheneer** [networktocode/diffsync#233]
Since we are calling subclasses of `diffsync.DiffSync`adapters in the examples and even in the docs

> When you initialize the `Diffsync` Adapter class

maybe we should just rename the class to `diffsync.Adapter`? To me this is clearer.

**Comment by chadell** [comment]
It looks good to me too

**Comment by Kircheneer** [comment]
We should keep the old name around for at least a couple of minor versions I think, but change the docs to point to the new one.

**Comment by Kircheneer** [comment]
Closed with #242
