### ISSUE TITLE
Possibly change "_src" and "_dst" keys in Diff.dict()?

### ISSUE THREAD

**Issue by glennmatthews** [networktocode/diffsync#34]
### Environment
* DiffSync version:  1.0.0

### Proposed Functionality

In the dict constructed by `Diff.dict()`, change the `_dst` and `_src` keys to something more intuitive, aesthetically pleasing, and/or "diff-like" -- perhaps `-` and `+`, or `<` and `>`?

### Use Case

The current "_src" and "_dst" keys were selected to avoid any likely conflict with the child DiffElement names, e.g.:

```
'DC1': {'_dst': {'parent_location_name': 'New York', 'status': 'in-transit'},
        '_src': {'parent_location_name': 'Tennessee', 'status': 'active'},
        'device': {...},
        'prefix': {...},
```

but they're kinda ugly as keys.

**Comment by glennmatthews** [comment]
Additionally the "src/source" and "dest/dst" names are themselves a bit confusing compared to the "diff" way of thinking - "source" is the data that changes will come from ("+", ">") and "dest" is the data that will be overwritten ("<", "-"). Maybe "dest" -> "current/base" and "source" -> "updated/new" renames would also be in order?

**Comment by PhillSimonds** [comment]
Looking at the data [here](https://github.com/networktocode/diffsync/pull/39) my mind gets a little tripped up by the '>' and '<'. It may just be me though. I think `+` and `-` would be more intuitive as keys, but that may just be preference..

**Comment by glennmatthews** [comment]
It is a bit unintuitive - I'd love to go a step further and change src/dest throughout as I mentioned in my comment above, as I think that would reduce the confusion (src == `>` or `+`, dst == `<` or `-`, which "feels" backwards to some extent), but that is a bigger change than I had time for at this moment. :)

As I reflect on this, I think I'm actually coming around about `-` and `+` as a solution... @dgarros do you have a preference?

**Comment by dgarros** [comment]
agreed I think `-` and `+` is easier to understand than `<` / `>`
