### ISSUE TITLE
Option to skip deletion of records on a case-by-case basis

### ISSUE THREAD

**Issue by glennmatthews** [networktocode/diffsync#49]
### Environment
* DiffSync version:  1.3.0

### Proposed Functionality

Add a model flag that can be used to control whether an unmatched model class or instance will trigger deletion (and/or creation) of records when a sync operation is run.

### Use Case

The existing global IGNORE_UNMATCHED_DST flag is not sufficiently granular as it applies to all records and all models. In some cases that may be adequate, but in others there needs to be per-model or even per-record control over this behavior -- for example, an application may not wish to delete unmatched Device records (perhaps a device is temporarily offline and hence not included in the source data), but may still wish to delete unmatched Interface records (as they reflect incorrect information about existing devices).

**Comment by dgarros** [comment]
@glennmatthews I think this has been fixed by #87
