### ISSUE TITLE
Support multiple types of datastore 

### ISSUE THREAD

**Issue by dgarros** [networktocode/diffsync#57]
### Environment
* DiffSync version:  1.3.0

### Proposed Functionality
Currently DiffSync Adapters are always leveraging an internal in-memory datastore that is storing the entire dataset. 
It would be great to support different types of datastore, like Redis in addition to the in-memory datastore.
As an option it would be useful to deactivate the internal datastore as well or provide a solution to pull the data directly from  the remote system.

### Use Case
When we are dealing with a large dataset, the volume of data stored in-memory can become very large and can present some challenges. And external datastore like Redis would reduce the volume of data stored in memory.
In some cases, DiffSync is running very closely to an existing database and duplicating the data in memory is redundant and inefficient.

**Comment by chadell** [comment]
First abstraction and Redis support done in #106
