### ISSUE TITLE
[Question] How to synchronise between different database engines?

### ISSUE THREAD

**Issue by aptly-io** [networktocode/diffsync#60]
### Environment
* DiffSync version:  1.3.0

### Proposed Functionality
Both Keepass and Bitwarden manage "credentials" but have a different schema and a way to access.
The examples 1 & 2 of diffsync describe the use of datasets with identical "schemas" and the same access.
The README.md confuses me (I don't seem to find what I look for).
 
1. Is diffsync the right module to try to synchronise these databases keepass and bitwarden?

2. Would this the way the creator of this module envisioned synchronisation:
  A sub class of `DiffSyncModel`. E.g. `CredModel` so that `DiffSync` can compare the important elements in a generic way.
  This could than be the base class for a `KeepassCredModel` and `BitwardenCredModel`.
  These 2 latter classes each have their specific `create`/`update`/`delete` class methods, 
  coping with the specific schema and access method.
  There would be 2 dataset classes:  `KeepassDataset` and `BitwardenDataset` both inheriting from `DiffSync`.

**Comment by glennmatthews** [comment]
Thanks for the question! This definitely is the kind of scenario that DiffSync is designed for; apologies for the lack of clarity in the documentation!

Your understanding as described in item 2 above appears to be entirely correct. The only point I would clarify is that, if you're only syncing in a single direction (e.g. from Keepass to Bitwarden only, never from Bitwarden to Keepass) then only one of your `DiffSyncModel` subclasses (the one representing the "destination" system) would need to actually  implement `create`/`update`/`delete` methods.

**Comment by aptly-io** [comment]
I have a follow-up question that I face during the implementation.
(see my original question for the types I use below; I hope their name describe their purpose).

One gets back a `diffsync.Diff` object after calling `KeepassDataset.diff_to(BitwardenDataset)`.
And from this `Diff` one gets access to `diffsync.DiffElement` which describes an action like create/update/delete.

Is there a clean way to retrieve the corresponding `CredModel` given this `DiffElement`?
Currently I use this ugly way: `KeepassDataset._data["CredModel"][DiffElement.name]`.

The reason for needing this `CredModel` is because it holds specific fields that are no longer available in `DiffElement`.
(only `_identifiers` and `_attributes` got copied in the `DiffElement`?)

**Comment by dgarros** [comment]
You should be able to retrieve it with `KeepassDataset.get("CredModel", DiffElement.name)`.

**Comment by aptly-io** [comment]
Thank you for this clarification!
