### ISSUE TITLE
Support current structlog major version.

### ISSUE THREAD

**Issue by grelleum** [networktocode/diffsync#74]
### Environment
* DiffSync version:  1.3.0

### Proposed Functionality
Currently the `pyproject.toml` file restricts `structlog` the major version to 20.
`structlog = "^20.1.0"`
The current major version is 21.

### Use Case
For my project, there is another required package that has pinned a minimum structlog version of 21.0.0.  When adding diffsync as a requirement to my project, pip will install a much older version of the other required package where the minimum structlog version was 20.  This causes an issue with needed features not being available.

**Comment by dgarros** [comment]
Fixed by #75
