### ISSUE TITLE
Create a new release on Pypi to include new changes

### ISSUE THREAD

**Issue by antoinedelia** [networktocode/diffsync#88]
Hi,

The last release 1.3.0 is from 30 April 2021. Since then, many new features were added (such as the `get_or_instantiate()` method).

It would be nice to make a new release to include these changes. This would also mean updating the CHANGELOG.md file.

Thanks.

**Comment by glennmatthews** [comment]
Agreed completely, thanks for raising this. I think we'd ideally like to merge or close #87 and then cut a new release immediately afterwards.

**Comment by dgarros** [comment]
1.4.0 has been released
